# Menu settings
menu:
  swpmanager_profile:
    name: My Profile
    url: "/lato/swpmanager/profile"
    icon: user
    position: 1
    permission: 0
  swpmanager_projects:
    name: Projects
    url: "/lato/swpmanager/projects"
    icon: web
    position: 2
    permission: 2
  swpmanager_clients:
    name: Clients
    url: "/lato/swpmanager/clients"
    icon: clients
    position: 3
    permission: 2
  swpmanager_collaborators:
    name: Collaborators
    url: "/lato/swpmanager/collaborators"
    icon: users
    position: 4
    permission: 2

# Custom assets settings
assets:
  swpmanager_application_css:
    name: lato_swpmanager/application
    type: css
  swpmanager_application_js:
    name: lato_swpmanager/application
    type: js
