# Menu settings
menu:
  swpmanager_profile:
    name: My Profile
    url: "/lato/swpmanager/profile"
    icon: user
    position: 9
    permission: 0
  swpmanager_projects:
    name: Projects
    url: "/lato/swpmanager/projects"
    icon: web
    position: 79
    permission: 2
  swpmanager_collaborators:
    name: Collaborators
    url: "/lato/swpmanager/collaborators"
    icon: users
    position: 89
    permission: 2

# Custom assets settings
assets:
  swpmanager_application_css:
    name: lato_swpmanager/application
    type: css
  swpmanager_application_js:
    name: lato_swpmanager/application
    type: js
