# Menu settings
menu:
  swpmanager:
    name: SW Projects
    url: "/lato/swpmanager"
    icon: web
    position: 79
    permission: 0

# Custom assets settings
assets:
  swpmanager_application_css:
    name: lato_swpmanager/application
    type: css
  swpmanager_application_js:
    name: lato_swpmanager/application
    type: js
